-- BE-002 core relational schema for resources, companies, profiles, recommendations,
-- claims, verification events, and media references.
BEGIN;

CREATE TABLE IF NOT EXISTS public.tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.resources (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    short_description text,
    official_url text,
    category varchar(120) NOT NULL DEFAULT 'General',
    stage varchar(80),
    location varchar(120),
    objective varchar(120),
    is_archived boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.resource_tags (
    resource_id integer NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
    tag_id integer NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (resource_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE,
    website text,
    employee_count integer,
    sector varchar(120) NOT NULL DEFAULT 'Unknown',
    stage varchar(80),
    year_founded integer,
    linkedin_url text,
    description text,
    address text,
    city varchar(120),
    county varchar(120),
    state varchar(20) NOT NULL DEFAULT 'UT',
    postal_code varchar(20),
    hiring_status varchar(40) NOT NULL DEFAULT 'unknown',
    latitude double precision,
    longitude double precision,
    job_postings jsonb NOT NULL DEFAULT '[]' :: jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_media (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    media_url text NOT NULL,
    media_type varchar(40) NOT NULL DEFAULT 'photo',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.founder_profiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    founder_name varchar(255),
    email varchar(255),
    stage varchar(80),
    industry varchar(120),
    location varchar(120),
    objective varchar(120),
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.recommendation_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    founder_profile_id integer NOT NULL REFERENCES public.founder_profiles(id) ON DELETE CASCADE,
    algorithm_version varchar(40) NOT NULL DEFAULT 'v1',
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.recommendation_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id integer NOT NULL REFERENCES public.recommendation_runs(id) ON DELETE CASCADE,
    resource_id integer NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
    rank integer NOT NULL,
    score numeric(5, 2) NOT NULL,
    rationale text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.claim_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    submitter_name varchar(255),
    submitter_email varchar(255) NOT NULL,
    STATUS varchar(40) NOT NULL DEFAULT 'pending',
    message text,
    requested_updates jsonb NOT NULL DEFAULT '{}' :: jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.verification_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_request_id integer NOT NULL REFERENCES public.claim_requests(id) ON DELETE CASCADE,
    event_type varchar(80) NOT NULL,
    actor_email varchar(255),
    notes text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_resources_stage ON public.resources(stage);

CREATE INDEX IF NOT EXISTS idx_resources_location ON public.resources(location);

CREATE INDEX IF NOT EXISTS idx_companies_sector ON public.companies(sector);

CREATE INDEX IF NOT EXISTS idx_companies_stage ON public.companies(stage);

CREATE INDEX IF NOT EXISTS idx_companies_hiring_status ON public.companies(hiring_status);

CREATE INDEX IF NOT EXISTS idx_companies_geo ON public.companies(latitude, longitude);

CREATE INDEX IF NOT EXISTS idx_recommendation_items_run_rank ON public.recommendation_items(run_id, rank);

CREATE INDEX IF NOT EXISTS idx_claim_requests_status ON public.claim_requests(STATUS);

COMMIT;