-- Align public schema with SQLAlchemy models in app/models.py
-- Safe to run multiple times.

begin;

create table if not exists public.resources (
    id bigint primary key,
    "Title" text,
    description text,
    "Communities" text,
    "Industries" text,
    "Locations" text,
    "Topics" text,
    link text,
    email text
);

alter table public.resources
    add column if not exists id bigint,
    add column if not exists "Title" text,
    add column if not exists description text,
    add column if not exists "Communities" text,
    add column if not exists "Industries" text,
    add column if not exists "Locations" text,
    add column if not exists "Topics" text,
    add column if not exists link text,
    add column if not exists email text;

alter table public.resources
    alter column "Title" type text,
    alter column description type text,
    alter column "Communities" type text,
    alter column "Industries" type text,
    alter column "Locations" type text,
    alter column "Topics" type text,
    alter column link type text,
    alter column email type text;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'resources_pkey'
          and conrelid = 'public.resources'::regclass
    ) then
        alter table public.resources
            add constraint resources_pkey primary key (id);
    end if;
end
$$;

create table if not exists public.companies (
    id integer generated by default as identity primary key,
    display_type text,
    linkedin text,
    startup_name text,
    full_address text,
    description text,
    website text,
    stage text,
    employees text,
    sector text,
    latitude double precision,
    longitude double precision
);

alter table public.companies
    add column if not exists id integer,
    add column if not exists display_type text,
    add column if not exists linkedin text,
    add column if not exists startup_name text,
    add column if not exists full_address text,
    add column if not exists description text,
    add column if not exists website text,
    add column if not exists stage text,
    add column if not exists employees text,
    add column if not exists sector text,
    add column if not exists latitude double precision,
    add column if not exists longitude double precision;

alter table public.companies
    alter column display_type type text,
    alter column linkedin type text,
    alter column startup_name type text,
    alter column full_address type text,
    alter column description type text,
    alter column website type text,
    alter column stage type text,
    alter column employees type text,
    alter column sector type text,
    alter column latitude type double precision,
    alter column longitude type double precision;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'companies_pkey'
          and conrelid = 'public.companies'::regclass
    ) then
        alter table public.companies
            add constraint companies_pkey primary key (id);
    end if;
end
$$;

commit;
