-- Align public schema with SQLAlchemy models in app/models.py
-- Safe to run multiple times.
BEGIN;

CREATE TABLE IF NOT EXISTS public.resources (
    id bigint PRIMARY KEY,
    "Title" text,
    description text,
    "Communities" text,
    "Industries" text,
    "Locations" text,
    "Topics" text,
    link text,
    email text
);

ALTER TABLE
    public.resources
ADD
    COLUMN IF NOT EXISTS id bigint,
ADD
    COLUMN IF NOT EXISTS "Title" text,
ADD
    COLUMN IF NOT EXISTS description text,
ADD
    COLUMN IF NOT EXISTS "Communities" text,
ADD
    COLUMN IF NOT EXISTS "Industries" text,
ADD
    COLUMN IF NOT EXISTS "Locations" text,
ADD
    COLUMN IF NOT EXISTS "Topics" text,
ADD
    COLUMN IF NOT EXISTS link text,
ADD
    COLUMN IF NOT EXISTS email text;

ALTER TABLE
    public.resources
ALTER COLUMN
    "Title" TYPE text,
ALTER COLUMN
    description TYPE text,
ALTER COLUMN
    "Communities" TYPE text,
ALTER COLUMN
    "Industries" TYPE text,
ALTER COLUMN
    "Locations" TYPE text,
ALTER COLUMN
    "Topics" TYPE text,
ALTER COLUMN
    link TYPE text,
ALTER COLUMN
    email TYPE text;

DO $ $ BEGIN IF NOT EXISTS (
    SELECT
        1
    FROM
        pg_constraint
    WHERE
        conname = 'resources_pkey'
        AND conrelid = 'public.resources' :: regclass
) THEN
ALTER TABLE
    public.resources
ADD
    CONSTRAINT resources_pkey PRIMARY KEY (id);

END IF;

END $ $;

CREATE TABLE IF NOT EXISTS public.companies (
    id integer generated by DEFAULT AS identity PRIMARY KEY,
    display_type text,
    linkedin text,
    startup_name text,
    full_address text,
    description text,
    website text,
    stage text,
    employees text,
    sector text,
    latitude double precision,
    longitude double precision
);

ALTER TABLE
    public.companies
ADD
    COLUMN IF NOT EXISTS id integer,
ADD
    COLUMN IF NOT EXISTS display_type text,
ADD
    COLUMN IF NOT EXISTS linkedin text,
ADD
    COLUMN IF NOT EXISTS startup_name text,
ADD
    COLUMN IF NOT EXISTS full_address text,
ADD
    COLUMN IF NOT EXISTS description text,
ADD
    COLUMN IF NOT EXISTS website text,
ADD
    COLUMN IF NOT EXISTS stage text,
ADD
    COLUMN IF NOT EXISTS employees text,
ADD
    COLUMN IF NOT EXISTS sector text,
ADD
    COLUMN IF NOT EXISTS latitude double precision,
ADD
    COLUMN IF NOT EXISTS longitude double precision;

ALTER TABLE
    public.companies
ALTER COLUMN
    display_type TYPE text,
ALTER COLUMN
    linkedin TYPE text,
ALTER COLUMN
    startup_name TYPE text,
ALTER COLUMN
    full_address TYPE text,
ALTER COLUMN
    description TYPE text,
ALTER COLUMN
    website TYPE text,
ALTER COLUMN
    stage TYPE text,
ALTER COLUMN
    employees TYPE text,
ALTER COLUMN
    sector TYPE text,
ALTER COLUMN
    latitude TYPE double precision,
ALTER COLUMN
    longitude TYPE double precision;

DO $ $ BEGIN IF NOT EXISTS (
    SELECT
        1
    FROM
        pg_constraint
    WHERE
        conname = 'companies_pkey'
        AND conrelid = 'public.companies' :: regclass
) THEN
ALTER TABLE
    public.companies
ADD
    CONSTRAINT companies_pkey PRIMARY KEY (id);

END IF;

END $ $;

COMMIT;