-- BE-008 self-service listing and claim workflow support fields and constraints.
BEGIN;

CREATE TABLE IF NOT EXISTS public.claim_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    submitter_name varchar(255),
    submitter_email varchar(255),
    STATUS varchar(40) NOT NULL DEFAULT 'pending',
    message text,
    requested_updates jsonb NOT NULL DEFAULT '{}' :: jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.verification_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_request_id integer NOT NULL REFERENCES public.claim_requests(id) ON DELETE CASCADE,
    event_type varchar(80) NOT NULL,
    actor_email varchar(255),
    notes text,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW()
);

ALTER TABLE
    public.claim_requests
ADD
    COLUMN IF NOT EXISTS user_id uuid;

CREATE INDEX IF NOT EXISTS idx_claim_requests_user_id ON public.claim_requests(user_id);

CREATE INDEX IF NOT EXISTS idx_claim_requests_company_status ON public.claim_requests(company_id, lower(STATUS));

CREATE INDEX IF NOT EXISTS idx_verification_events_claim_request_id ON public.verification_events(claim_request_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_requests_one_pending_per_user ON public.claim_requests(user_id)
WHERE
    user_id IS NOT NULL
    AND lower(STATUS) = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_requests_one_active_per_company ON public.claim_requests(company_id)
WHERE
    lower(STATUS) IN ('pending', 'verified');

COMMIT;